//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Block.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Control_Block.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bf_rail_piston {
            get {
                object obj = ResourceManager.GetObject("bf_rail_piston", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_base.mtl
        ///o Cube.000_Cube.006
        ///v 0.125000 0.500000 0.400000
        ///v 0.125000 0.500000 0.500000
        ///v 0.500000 -0.500000 0.400000
        ///v 0.500000 -0.500000 0.500000
        ///v 0.500000 0.500000 0.400000
        ///v 0.500000 0.500000 0.500000
        ///v -0.500000 -0.500000 0.400000
        ///v -0.500000 -0.500000 0.500000
        ///v -0.500000 0.500000 0.400000
        ///v -0.500000 0.500000 0.500000
        ///v -0.125000 0.500000 0.400000
        ///v -0.125000 0.500000 0.500000
        ///v 0.250000 -0.437500 0.1750 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_base {
            get {
                return ResourceManager.GetString("bf_rail_piston_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_base.mtl
        ///o Cube.000_Cube.006
        ///v 0.125000 0.500000 0.400000
        ///v 0.125000 0.500000 0.500000
        ///v 0.500000 -0.500000 0.400000
        ///v 0.500000 -0.500000 0.500000
        ///v 0.500000 0.500000 0.400000
        ///v 0.500000 0.500000 0.500000
        ///v -0.500000 -0.500000 0.400000
        ///v -0.500000 -0.500000 0.500000
        ///v -0.500000 0.500000 0.400000
        ///v -0.500000 0.500000 0.500000
        ///v -0.125000 0.500000 0.400000
        ///v -0.125000 0.500000 0.500000
        ///v 0.250000 -0.437500 0.1750 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_base1 {
            get {
                return ResourceManager.GetString("bf_rail_piston_base1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_corner.mtl
        ///o Cube.008_Cube.012
        ///v -0.300000 -0.500000 0.150000
        ///v 0.240000 -0.500000 0.400000
        ///v -0.500000 -0.400000 -0.400000
        ///v -0.400000 -0.400000 -0.500000
        ///v -0.400000 -0.500000 -0.400000
        ///v -0.500000 0.400000 -0.400000
        ///v 0.400000 -0.500000 -0.400000
        ///v -0.500000 -0.400000 0.400000
        ///v -0.400000 -0.500000 0.400000
        ///v -0.500000 0.400000 0.400000
        ///v 0.400000 -0.500000 0.400000
        ///v 0.400000 -0.500000 -0.300000
        ///v 0.400000  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_corner {
            get {
                return ResourceManager.GetString("bf_rail_piston_corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_corner_2.mtl
        ///o Cube.005_Cube.000
        ///v 0.006398 0.498208 0.150000
        ///v 0.505066 0.164547 0.150000
        ///v 0.505066 0.164547 -0.125000
        ///v 0.359829 0.261726 0.125000
        ///v 0.004320 0.499599 -0.125000
        ///v 0.151843 0.400891 -0.125000
        ///v 0.359621 0.261865 -0.125000
        ///v 0.151687 0.400995 0.125000
        ///v -0.001110 0.121802 0.125000
        ///v 0.229967 0.026064 -0.125000
        ///v -0.000995 0.121754 -0.125000
        ///v -0.164978 0.189695 -0.125000
        ///v 0.230198 0.025968 0.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_corner_2 {
            get {
                return ResourceManager.GetString("bf_rail_piston_corner_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_extension.mtl
        ///o Cube.001_Cube.003
        ///v 0.125000 -0.500000 0.400000
        ///v 0.125000 -0.500000 0.500000
        ///v 0.125000 0.500000 0.400000
        ///v 0.125000 0.500000 0.500000
        ///v 0.500000 -0.500000 0.400000
        ///v 0.500000 -0.500000 0.500000
        ///v 0.500000 0.500000 0.400000
        ///v 0.500000 0.500000 0.500000
        ///v -0.500000 -0.500000 0.400000
        ///v -0.500000 -0.500000 0.500000
        ///v -0.500000 0.500000 0.400000
        ///v -0.500000 0.500000 0.500000
        ///v -0.125000 -0.500000  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_extension {
            get {
                return ResourceManager.GetString("bf_rail_piston_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_extension_2.mtl
        ///o Cube.003_Cube.015
        ///v 0.300000 -0.500000 0.150000
        ///v -0.300000 -0.500000 0.150000
        ///v 0.300000 -0.500000 -0.125000
        ///v 0.300000 0.500000 -0.400000
        ///v -0.400000 0.500000 0.300000
        ///v 0.300000 0.500000 -0.125000
        ///v -0.500000 -0.400000 -0.400000
        ///v -0.400000 -0.400000 -0.500000
        ///v -0.400000 -0.500000 -0.400000
        ///v -0.500000 -0.100000 -0.400000
        ///v -0.400000 0.000000 -0.400000
        ///v -0.400000 -0.100000 -0.500000
        ///v 0.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_extension_2 {
            get {
                return ResourceManager.GetString("bf_rail_piston_extension_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_extension.mtl
        ///o Cube.001_Cube.003
        ///v 0.125000 -0.500000 0.400000
        ///v 0.125000 -0.500000 0.500000
        ///v 0.125000 0.500000 0.400000
        ///v 0.125000 0.500000 0.500000
        ///v 0.500000 -0.500000 0.400000
        ///v 0.500000 -0.500000 0.500000
        ///v 0.500000 0.500000 0.400000
        ///v 0.500000 0.500000 0.500000
        ///v -0.500000 -0.500000 0.400000
        ///v -0.500000 -0.500000 0.500000
        ///v -0.500000 0.500000 0.400000
        ///v -0.500000 0.500000 0.500000
        ///v -0.125000 -0.500000  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_extension1 {
            get {
                return ResourceManager.GetString("bf_rail_piston_extension1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_head.mtl
        ///o Plane.001_Plane.006
        ///v -0.302500 0.125000 0.150000
        ///v -0.302500 -0.125000 0.150000
        ///v 0.302500 -0.125000 0.150000
        ///v 0.302500 0.125000 0.150000
        ///v -0.302500 0.125000 -0.010000
        ///v -0.302500 -0.125000 -0.010000
        ///v 0.302500 -0.125000 -0.010000
        ///v 0.302500 0.125000 -0.010000
        ///v 0.200000 0.125000 0.200000
        ///v -0.200000 0.125000 0.200000
        ///v -0.200000 -0.125000 0.200000
        ///v 0.200000 -0.125000 0.200000
        ///v -0.200000 0.12500 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_head {
            get {
                return ResourceManager.GetString("bf_rail_piston_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_head.mtl
        ///o Plane.001_Plane.006
        ///v -0.302500 0.125000 0.150000
        ///v -0.302500 -0.125000 0.150000
        ///v 0.302500 -0.125000 0.150000
        ///v 0.302500 0.125000 0.150000
        ///v -0.302500 0.125000 -0.010000
        ///v -0.302500 -0.125000 -0.010000
        ///v 0.302500 -0.125000 -0.010000
        ///v 0.302500 0.125000 -0.010000
        ///v 0.200000 0.125000 0.200000
        ///v -0.200000 0.125000 0.200000
        ///v -0.200000 -0.125000 0.200000
        ///v 0.200000 -0.125000 0.200000
        ///v -0.200000 0.12500 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_head1 {
            get {
                return ResourceManager.GetString("bf_rail_piston_head1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_wedge.mtl
        ///o m_BF_Streamline_111.002
        ///v -0.400000 -0.400000 -0.500000
        ///v -0.400000 -0.500000 -0.400000
        ///v -0.500000 -0.400000 0.391500
        ///v -0.400000 -0.500000 0.400000
        ///v -0.500001 -0.323976 0.384934
        ///v -0.500000 -0.400000 -0.200000
        ///v -0.500000 -0.400000 0.200000
        ///v -0.400000 -0.500000 0.300000
        ///v -0.300000 -0.500000 0.400000
        ///v -0.300000 -0.500000 -0.400000
        ///v -0.500000 0.333589 -0.154717
        ///v -0.200000 -0.500000 -0.250000
        ///v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_wedge {
            get {
                return ResourceManager.GetString("bf_rail_piston_wedge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;bf_rail_piston.blend&apos;
        ///# www.blender.org
        ///mtllib bf_rail_piston_wedge_2.mtl
        ///o Cube.002_Cube.004
        ///v 0.300000 1.150000 -0.499998
        ///v -0.300000 1.150000 -0.499998
        ///v 0.300000 0.875000 -0.499998
        ///v 0.300000 0.471924 0.472868
        ///v 0.300000 0.666284 0.667416
        ///v -0.300000 0.666284 0.667416
        ///v 0.125250 1.125000 -0.499998
        ///v -0.125250 0.648614 0.649730
        ///v 0.125250 0.648614 0.649730
        ///v 0.240000 0.842974 0.844279
        ///v 0.240000 1.400000 -0.499998
        ///v -0.240001 0.687487 0.688640
        ///v -0.240000 1.180000 -0.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bf_rail_piston_wedge_2 {
            get {
                return ResourceManager.GetString("bf_rail_piston_wedge_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bf_rail_segment {
            get {
                object obj = ResourceManager.GetObject("bf_rail_segment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bf_rail_segment_corner {
            get {
                object obj = ResourceManager.GetObject("bf_rail_segment_corner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bf_rail_segment_corner_large {
            get {
                object obj = ResourceManager.GetObject("bf_rail_segment_corner_large", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bf_rail_segment_long {
            get {
                object obj = ResourceManager.GetObject("bf_rail_segment_long", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bf_rail_segment_streamline {
            get {
                object obj = ResourceManager.GetObject("bf_rail_segment_streamline", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bf_rail_segment_streamline_large {
            get {
                object obj = ResourceManager.GetObject("bf_rail_segment_streamline_large", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;BFpiston.blend&apos;
        ///# www.blender.org
        ///mtllib BFp_blockbottom.mtl
        ///o m_BF_MotionEngine_Linear_112_Base_Instance
        ///v 0.101537 0.499999 -0.378939
        ///v 0.277403 0.499999 -0.277403
        ///v -0.277403 0.499999 -0.277403
        ///v -0.146954 -0.314892 -0.500000
        ///v 0.107356 -0.428834 -0.500000
        ///v 0.146954 -0.314892 -0.500000
        ///v -0.107356 -0.428834 -0.499999
        ///v 0.126918 -0.500001 -0.428833
        ///v 0.366017 -0.428834 -0.366017
        ///v -0.500000 -0.428834 -0.107355
        ///v -0.500000 -0.314892 -0.146953
        ///v -0.500000 - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BFp_blockbottom {
            get {
                return ResourceManager.GetString("BFp_blockbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;BFpiston.blend&apos;
        ///# www.blender.org
        ///mtllib BFp_blocktop.mtl
        ///o m_BF_MotionEngine_Linear_112_Base_Instance.001
        ///v -0.146954 0.428834 -0.500000
        ///v -0.366017 0.428834 -0.366018
        ///v 0.126918 0.500000 -0.428834
        ///v -0.500000 0.428834 -0.146954
        ///v -0.428834 0.500000 -0.126919
        ///v 0.146954 0.428834 0.500000
        ///v -0.146954 0.428834 0.500000
        ///v -0.315695 0.500000 0.315695
        ///v -0.126918 0.500000 0.428833
        ///v 0.126918 0.500000 0.428833
        ///v -0.366017 0.428834 0.366017
        ///v -0.500000 0.428834 0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BFp_blocktop {
            get {
                return ResourceManager.GetString("BFp_blocktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BFp_png {
            get {
                object obj = ResourceManager.GetObject("BFp_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] friction_pad_gc_big_png {
            get {
                object obj = ResourceManager.GetObject("friction_pad_gc_big_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] friction_pad_gc_small_png {
            get {
                object obj = ResourceManager.GetObject("friction_pad_gc_small_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 75) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib GCfrictionpadbig.mtl
        ///o m_BF_Block_Faired_111_Instance.001
        ///v -0.000002 0.600000 1.000000
        ///v 0.132021 0.500000 1.132023
        ///v 0.132021 0.500000 0.867977
        ///v -0.132024 0.500000 1.132023
        ///v -0.132024 0.500000 0.867977
        ///v 0.999998 0.600000 1.000000
        ///v 1.132021 0.500000 1.132023
        ///v 1.132021 0.500000 0.867977
        ///v 0.867976 0.500000 1.132023
        ///v 0.867976 0.500000 0.867977
        ///v -0.000002 0.600000 0.000000
        ///v 0.132021 0.500000 0.132023
        ///v 0.132021 0.500000 -0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GCfrictionpadbig {
            get {
                return ResourceManager.GetString("GCfrictionpadbig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 75) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib GCfrictionpadsmall.mtl
        ///o Cylinder
        ///v -0.500000 0.412500 0.000000
        ///v -0.461940 0.412500 -0.191342
        ///v -0.374574 0.410860 -0.155154
        ///v -0.386661 0.410033 -0.103913
        ///v -0.396994 0.410033 -0.051966
        ///v -0.405436 0.410860 0.000000
        ///v 0.000000 0.500000 0.000000
        ///v 0.191342 0.500000 -0.461940
        ///v 0.000000 0.500000 -0.500000
        ///v -0.191342 0.412500 0.461940
        ///v -0.353553 0.412500 0.353554
        ///v -0.286686 0.410860 0.286686
        ///v -0.243972 0.410033 0.317463
        ///v -0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GCfrictionpadsmall {
            get {
                return ResourceManager.GetString("GCfrictionpadsmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GEO_piston.blend&apos;
        ///# www.blender.org
        ///mtllib GEOp_blockbottom.mtl
        ///o geo_block_bottom
        ///v -0.258274 0.344012 0.659851
        ///v -0.258274 0.557951 0.659851
        ///v -0.371306 0.557951 0.613032
        ///v -0.371306 0.344012 0.613032
        ///v -0.418125 0.557951 0.500000
        ///v -0.418125 0.344012 0.500000
        ///v -0.371306 0.557951 0.386968
        ///v -0.371306 0.344012 0.386968
        ///v -0.258274 0.557951 0.340149
        ///v -0.258274 0.344012 0.340149
        ///v 0.030684 0.344012 0.659851
        ///v 0.030684 0.557951 0.659851
        ///v 0.030684 0.557951  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEOp_blockbottom {
            get {
                return ResourceManager.GetString("GEOp_blockbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GEO_piston.blend&apos;
        ///# www.blender.org
        ///mtllib GEOp_blocktop.mtl
        ///o geo_block_top
        ///v 1.500000 0.552534 -0.045250
        ///v 1.500000 0.552534 -0.300020
        ///v 1.500000 0.965657 -0.300020
        ///v 1.441378 0.552534 -0.045250
        ///v 1.500000 0.369114 0.103227
        ///v 1.441378 0.369114 0.103227
        ///v 1.300020 1.300020 -0.500000
        ///v 1.300020 1.500000 -0.300020
        ///v 1.500000 1.300020 -0.300020
        ///v 1.045250 0.552534 -0.500000
        ///v 0.896773 0.369114 -0.500000
        ///v 0.103227 0.369114 -0.500000
        ///v -0.045250 0.552534 -0.50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEOp_blocktop {
            get {
                return ResourceManager.GetString("GEOp_blocktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GEOp_icon_png {
            get {
                object obj = ResourceManager.GetObject("GEOp_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GEO_piston.blend&apos;
        ///# www.blender.org
        ///mtllib GEOp_shaftbottom.mtl
        ///o geo_piston_bottom
        ///v 1.185176 -0.160939 0.104413
        ///v 0.895587 -0.160939 -0.185176
        ///v 0.895587 1.131227 -0.185176
        ///v 1.185176 1.131227 0.104413
        ///v 0.500000 -0.160939 -0.291174
        ///v 0.500000 1.131227 -0.291174
        ///v 0.104413 -0.160939 -0.185176
        ///v 0.104413 1.131227 -0.185176
        ///v -0.185176 -0.160939 0.104413
        ///v -0.185176 1.131227 0.104413
        ///v -0.291174 -0.160939 0.500000
        ///v -0.291174 1.131227 0.500000
        ///v -0.185176 - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEOp_shaftbottom {
            get {
                return ResourceManager.GetString("GEOp_shaftbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GEO_piston.blend&apos;
        ///# www.blender.org
        ///mtllib GEOp_shafttop.mtl
        ///o geo_piston_top
        ///v 1.064939 0.513169 0.173832
        ///v 0.826168 0.513169 -0.064939
        ///v 0.826168 1.486831 -0.064939
        ///v 1.064939 1.486831 0.173832
        ///v 0.500000 0.513169 -0.152335
        ///v 0.500000 1.486831 -0.152335
        ///v 0.173832 0.513169 -0.064939
        ///v 0.173832 1.486831 -0.064939
        ///v -0.064939 0.513169 0.173832
        ///v -0.064939 1.486831 0.173832
        ///v -0.152335 0.513169 0.500000
        ///v -0.152335 1.486831 0.500000
        ///v -0.064939 0.513169 0.82 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEOp_shafttop {
            get {
                return ResourceManager.GetString("GEOp_shafttop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_blockbottom.mtl
        ///o the_node.014_tri_420_geometry.000
        ///v -0.468440 0.374719 -0.312560
        ///v -0.468440 -0.375040 -0.312146
        ///v -0.468440 -0.000159 0.062318
        ///v 0.468759 0.374719 -0.468760
        ///v 0.312559 0.374719 -0.468760
        ///v 0.312559 0.374719 -0.312560
        ///v 0.468759 0.374719 -0.312560
        ///v 0.468759 -0.000159 0.062318
        ///v 0.468759 -0.375040 -0.312145
        ///v -0.312240 0.374719 -0.468760
        ///v -0.312240 0.374719 -0.312560
        ///v 0.312559 -0.375040 -0.468760
        ///v -0.31224 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_blockbottom {
            get {
                return ResourceManager.GetString("HEp_blockbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_blocktop.mtl
        ///o the_node.002_tri_420_geometry.000
        ///v -0.468440 -0.374719 0.312560
        ///v -0.468440 0.375040 0.312145
        ///v -0.468440 0.000159 -0.062319
        ///v 0.468759 -0.374719 0.468760
        ///v 0.312559 -0.374719 0.468760
        ///v 0.312559 -0.374719 0.312560
        ///v 0.468759 -0.374719 0.312560
        ///v 0.468759 0.000159 -0.062319
        ///v 0.468759 0.375040 0.312145
        ///v -0.312240 -0.374719 0.468760
        ///v -0.312240 -0.374719 0.312560
        ///v 0.312559 0.375040 0.468760
        ///v -0.312240 0.37504 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_blocktop {
            get {
                return ResourceManager.GetString("HEp_blocktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HEp_icon_png {
            get {
                object obj = ResourceManager.GetObject("HEp_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_shaftbottom.mtl
        ///o the_node.006_tri_420_geometry.001
        ///v -0.327860 -0.000321 0.327859
        ///v -0.437200 -0.000321 0.327859
        ///v -0.437200 -0.000321 0.437199
        ///v -0.327860 -0.000321 0.437199
        ///v 0.437519 -0.500160 -0.328180
        ///v 0.437519 -0.000320 -0.328180
        ///v 0.437519 -0.000320 -0.000160
        ///v 0.437519 -0.500160 -0.000160
        ///v -0.327860 -0.000321 -0.328180
        ///v -0.437200 -0.000321 -0.328180
        ///v -0.437200 -0.000321 -0.000160
        ///v -0.327860 -0.000321 -0.000160
        ///v  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_shaftbottom {
            get {
                return ResourceManager.GetString("HEp_shaftbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;HE_piston.blend&apos;
        ///# www.blender.org
        ///mtllib HEp_shaftmidb.mtl
        ///o the_node.018_tri_420_geometry.020
        ///v 0.312559 0.499359 0.312239
        ///v -0.312240 -0.437841 -0.312560
        ///v 0.312559 -0.437840 -0.312560
        ///v -0.312240 -0.437841 0.312239
        ///v 0.312559 -0.437840 0.312240
        ///v -0.312240 0.499359 -0.312560
        ///v 0.312559 0.499359 -0.312560
        ///v -0.312240 0.499359 0.312239
        ///v -0.312240 -0.437841 -0.000160
        ///v 0.312559 0.499359 -0.000160
        ///v 0.312559 -0.437840 -0.000160
        ///v -0.312240 0.499359 -0.00016 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_shaftmidb {
            get {
                return ResourceManager.GetString("HEp_shaftmidb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_shaftmidt.mtl
        ///o the_node.019_tri_420_geometry.021
        ///v 0.281319 -0.500641 -0.211030
        ///v 0.281319 0.436559 -0.211030
        ///v 0.281319 0.436559 -0.000161
        ///v 0.281319 -0.500641 -0.000160
        ///v 0.281319 0.436559 0.210709
        ///v 0.281319 -0.500641 0.210709
        ///v 0.211029 -0.500641 -0.281320
        ///v 0.000159 -0.500641 -0.281320
        ///v 0.000159 0.436559 -0.281320
        ///v 0.211029 0.436559 -0.281320
        ///v -0.210710 -0.500641 -0.281320
        ///v -0.210711 0.436559 -0.281320
        ///v -0.281000 -0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_shaftmidt {
            get {
                return ResourceManager.GetString("HEp_shaftmidt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_shafttop.mtl
        ///o the_node.013_tri_420_geometry.002
        ///v -0.327860 0.000321 -0.327860
        ///v -0.437200 0.000321 -0.327860
        ///v -0.437200 0.000321 -0.437200
        ///v -0.327860 0.000321 -0.437200
        ///v 0.437519 0.500160 0.328180
        ///v 0.437519 0.000321 0.328180
        ///v 0.437519 0.000321 0.000160
        ///v 0.437519 0.500160 0.000160
        ///v -0.327860 0.000321 0.328180
        ///v -0.437200 0.000321 0.328180
        ///v -0.437200 0.000321 0.000160
        ///v -0.327860 0.000321 0.000160
        ///v -0.437200 0.500160  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_shafttop {
            get {
                return ResourceManager.GetString("HEp_shafttop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEps_base.mtl
        ///o Cube.045_Cube.086
        ///v 0.400000 -0.500000 -0.500000
        ///v 0.500000 -0.400000 -0.400000
        ///v 0.400000 -0.500000 -0.400000
        ///v -0.400000 -0.500000 -0.400000
        ///v -0.500000 -0.400000 -0.500000
        ///v -0.400000 -0.500000 -0.500000
        ///v 0.300000 0.400000 -0.400000
        ///v 0.300000 0.400000 -0.300000
        ///v 0.400000 0.500000 -0.300000
        ///v -0.400000 -0.400000 -0.300000
        ///v -0.500000 -0.400000 -0.400000
        ///v 0.400000 -0.400000 -0.300000
        ///v 0.500000 -0.100000 -0.400000
        ///v 0.450000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEps_base {
            get {
                return ResourceManager.GetString("HEps_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEps_deco_base.mtl
        ///o Cube.008_Cube.034
        ///v 0.400000 -0.500000 -0.300000
        ///v 0.400000 -0.500000 -0.500000
        ///v 0.500000 -0.500000 -0.500000
        ///v 0.500000 -0.500000 -0.400000
        ///v -0.400000 -0.500000 -0.500000
        ///v -0.400000 -0.500000 -0.300000
        ///v -0.500000 -0.500000 -0.400000
        ///v -0.500000 -0.500000 -0.500000
        ///v 0.400000 0.490000 -0.500000
        ///v 0.350000 0.450000 -0.500000
        ///v 0.350000 0.450000 -0.450000
        ///v 0.300000 0.400000 -0.400000
        ///v 0.300000 0.400000 -0.300000
        ///v 0.4000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEps_deco_base {
            get {
                return ResourceManager.GetString("HEps_deco_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEps_deco_head.mtl
        ///o Cube.010_Cube.036
        ///v -0.380000 -0.500000 -0.340000
        ///v -0.380000 0.510000 -0.340000
        ///v -0.470000 0.510000 -0.460000
        ///v -0.470000 -0.500000 -0.460000
        ///v -0.300000 0.450000 -0.460000
        ///v -0.250000 0.400000 -0.460000
        ///v 0.250000 0.400000 -0.460000
        ///v 0.300000 0.450000 -0.460000
        ///v 0.470000 0.510000 -0.460000
        ///v 0.470000 -0.500000 -0.460000
        ///v 0.380000 0.510000 -0.340000
        ///v 0.380000 -0.500000 -0.340000
        ///v 0.300000 0.450000 -0.340000
        ///v 0.250000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEps_deco_head {
            get {
                return ResourceManager.GetString("HEps_deco_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEps_deco_shaft.mtl
        ///o Cube.009_Cube.035
        ///v -0.390000 -0.500000 -0.320000
        ///v -0.390000 0.450000 -0.320000
        ///v -0.490000 0.450000 -0.480000
        ///v -0.490000 -0.500000 -0.480000
        ///v -0.300000 0.450000 -0.480000
        ///v -0.250000 0.400000 -0.480000
        ///v 0.250000 0.400000 -0.480000
        ///v 0.300000 0.450000 -0.480000
        ///v 0.490000 0.450000 -0.480000
        ///v 0.490000 -0.500000 -0.480000
        ///v 0.390000 0.450000 -0.320000
        ///v 0.390000 -0.500000 -0.320000
        ///v 0.300000 0.450000 -0.320000
        ///v 0.25000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEps_deco_shaft {
            get {
                return ResourceManager.GetString("HEps_deco_shaft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEps_head.mtl
        ///o Cube.048_Cube.089
        ///v 0.500000 1.400000 -0.400000
        ///v 0.400000 1.500000 -0.500000
        ///v 0.400000 1.500000 -0.400000
        ///v -0.500000 1.400000 -0.500000
        ///v -0.400000 1.500000 -0.400000
        ///v -0.400000 1.500000 -0.500000
        ///v 0.400000 0.500000 -0.300000
        ///v 0.300000 0.600000 -0.400000
        ///v 0.350000 0.550000 -0.450000
        ///v -0.400000 1.400000 -0.300000
        ///v -0.500000 1.400000 -0.400000
        ///v 0.400000 1.400000 -0.300000
        ///v 0.450000 1.100000 -0.400000
        ///v 0.500000 1.100000  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEps_head {
            get {
                return ResourceManager.GetString("HEps_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEps_shaft_1.mtl
        ///o Cube.046_Cube.087
        ///v -0.400000 -0.200000 -0.320000
        ///v -0.400000 0.500000 -0.320000
        ///v -0.450000 0.500000 -0.480000
        ///v -0.450000 -0.200000 -0.480000
        ///v -0.200000 0.560000 -0.480000
        ///v -0.150000 0.510000 -0.480000
        ///v 0.150000 0.510000 -0.480000
        ///v 0.200000 0.560000 -0.480000
        ///v 0.450000 0.500000 -0.480000
        ///v 0.450000 -0.190000 -0.480000
        ///v 0.400000 0.500000 -0.320000
        ///v 0.400000 -0.190000 -0.320000
        ///v 0.200000 0.500000 -0.320000
        ///v 0.150000 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEps_shaft_1 {
            get {
                return ResourceManager.GetString("HEps_shaft_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEps_shaft_2.mtl
        ///o Cube.047_Cube.088
        ///v -0.380000 -0.100000 -0.340000
        ///v -0.380000 1.100000 -0.340000
        ///v -0.430000 1.100000 -0.460000
        ///v -0.430000 -0.100000 -0.460000
        ///v -0.200000 0.560000 -0.460000
        ///v -0.150000 0.510000 -0.460000
        ///v 0.150000 0.510000 -0.460000
        ///v 0.200000 0.560000 -0.460000
        ///v 0.430000 1.110000 -0.460000
        ///v 0.430000 -0.090000 -0.460000
        ///v 0.380000 1.110000 -0.340000
        ///v 0.380000 -0.090000 -0.340000
        ///v 0.200000 0.500000 -0.340000
        ///v 0.150000 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEps_shaft_2 {
            get {
                return ResourceManager.GetString("HEps_shaft_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEps_shaft_3.mtl
        ///o Cube.049_Cube.090
        ///v -0.400000 1.200000 -0.320000
        ///v -0.450000 1.200000 -0.480000
        ///v -0.450000 0.500000 -0.480000
        ///v -0.400000 0.500000 -0.320000
        ///v 0.450000 1.200000 -0.480000
        ///v 0.450000 0.500000 -0.480000
        ///v 0.200000 0.560000 -0.480000
        ///v 0.150000 0.610000 -0.480000
        ///v -0.150000 0.610000 -0.480000
        ///v -0.200000 0.560000 -0.480000
        ///v 0.400000 1.200000 -0.320000
        ///v 0.400000 0.500000 -0.320000
        ///v -0.200000 0.500000 -0.320000
        ///v -0.150000 0.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEps_shaft_3 {
            get {
                return ResourceManager.GetString("HEps_shaft_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib mtmag ball.mtl
        ///o m_BF_Block_Faired_111_Instance.001
        ///v -0.450001 -0.400000 -0.499999
        ///v 0.449999 -0.400000 -0.500000
        ///v 0.499999 -0.400000 -0.450001
        ///v -0.500001 -0.400000 -0.449999
        ///v -0.500000 -0.400000 0.450001
        ///v 0.450000 -0.400000 0.499999
        ///v -0.450000 -0.400000 0.500000
        ///v 0.500000 -0.400000 0.449999
        ///v -0.000000 -0.160000 -0.003982
        ///v 0.499999 -0.500000 -0.500001
        ///v -0.500001 -0.500000 -0.500000
        ///v -0.500000 -0.500000 0.500000
        ///v 0.5000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_ball {
            get {
                return ResourceManager.GetString("mtmag_ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib mtmag ball collider.mtl
        ///o Cone
        ///v 0.000000 -0.500000 -0.500000
        ///v 0.000000 -0.200000 -0.250000
        ///v 0.353553 -0.500000 -0.353553
        ///v 0.176777 -0.200000 -0.176777
        ///v 0.500000 -0.500000 0.000000
        ///v 0.250000 -0.200000 0.000000
        ///v 0.353553 -0.500000 0.353553
        ///v 0.176777 -0.200000 0.176777
        ///v -0.000000 -0.500000 0.500000
        ///v -0.000000 -0.200000 0.250000
        ///v -0.353553 -0.500000 0.353553
        ///v -0.176777 -0.200000 0.176777
        ///v -0.500000 -0.500000 -0.000000
        ///v  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_ball_collider {
            get {
                return ResourceManager.GetString("mtmag_ball_collider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 47) OBJ File: &apos;Ball.blend&apos;
        ///# www.blender.org
        ///mtllib mtmag ball collider large.mtl
        ///o Cone
        ///v -0.207106 -0.500000 -0.207106
        ///v 0.500000 0.100000 -0.000000
        ///v 0.853554 0.100000 0.146446
        ///v 1.207106 -0.500000 -0.207106
        ///v 1.000000 0.100000 0.500000
        ///v 0.853554 0.100000 0.853554
        ///v 1.207106 -0.500000 1.207106
        ///v 0.500000 0.100000 1.000000
        ///v 0.146446 0.100000 0.853554
        ///v -0.207106 -0.500000 1.207106
        ///v 0.000000 0.100000 0.500000
        ///v 0.146446 0.100000 0.146446
        ///v 1.207106 -0.148527 0.500000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_ball_collider_large {
            get {
                return ResourceManager.GetString("mtmag_ball_collider_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 47) OBJ File: &apos;Ball.blend&apos;
        ///# www.blender.org
        ///mtllib mtmag ball collider large.mtl
        ///o m_BF_Block_Faired_111_Instance.001
        ///v 0.786182 -0.247577 1.190903
        ///v 0.213819 -0.247577 -0.190903
        ///v 0.500000 -0.250000 1.191324
        ///v 0.786181 -0.247577 -0.190903
        ///v 0.213819 -0.247577 1.190903
        ///v 1.190903 -0.247577 0.213819
        ///v 0.500000 -0.250000 -0.191324
        ///v 0.500000 -0.500000 -0.145367
        ///v 0.189096 -0.497458 -0.145108
        ///v -0.146268 -0.497472 -0.145367
        ///v -0.145340 -0.497579 0.190105
        ///v -0.145930 -0.5000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_ball_large {
            get {
                return ResourceManager.GetString("mtmag_ball_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mtmag_ball_large_png {
            get {
                object obj = ResourceManager.GetObject("mtmag_ball_large_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mtmag_ball_png {
            get {
                object obj = ResourceManager.GetObject("mtmag_ball_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib mtmag fixed.mtl
        ///o m_BF_Block_Faired_111_Instance.001_m_BF_Block_Faired_111_Instance.009
        ///v 0.450000 -0.000000 0.125000
        ///v -0.405000 -0.000000 -0.450000
        ///v 0.125000 -0.000000 0.450000
        ///v 0.450000 -0.000000 0.405000
        ///v 0.450000 -0.000000 -0.405000
        ///v -0.450000 -0.000000 -0.125000
        ///v -0.405000 -0.000000 0.450000
        ///v 0.125000 -0.000000 -0.450000
        ///v -0.125000 -0.000000 -0.450000
        ///v -0.450000 -0.000000 0.405000
        ///v 0.450000 -0.000000 -0.125000
        ///v -0.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_fixed {
            get {
                return ResourceManager.GetString("mtmag_fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib mtmag swivel large.mtl
        ///o Plane.001
        ///v 0.146447 -0.500000 1.500000
        ///v 0.323223 -0.500000 1.500000
        ///v 0.423223 -0.300003 1.500000
        ///v 0.146447 -0.050003 1.499317
        ///v 0.500000 -0.064148 1.400322
        ///v 0.500000 0.399989 1.390877
        ///v 0.853553 0.399989 1.340877
        ///v 0.853553 -0.064148 1.400322
        ///v 0.500000 -0.050003 1.499317
        ///v 0.853553 -0.050003 1.499317
        ///v 0.853553 0.399993 1.418785
        ///v 0.853553 -0.500000 1.500000
        ///v 0.853553 -0.500000 1.401005
        ///v 0.146447  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_swivel_large {
            get {
                return ResourceManager.GetString("mtmag_swivel_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;piston.blend&apos;
        ///# www.blender.org
        ///mtllib piston_base.mtl
        ///o Cylinder
        ///v 0.000000 -0.490000 -0.500000
        ///v 0.000000 0.141421 -0.500000
        ///v 0.191342 -0.490000 -0.461940
        ///v 0.191342 0.250000 -0.461940
        ///v 0.353553 -0.490000 -0.353553
        ///v 0.353553 0.250000 -0.353553
        ///v 0.461940 -0.490000 -0.191342
        ///v 0.461940 0.250000 -0.191342
        ///v 0.500000 -0.490000 0.000000
        ///v 0.500000 0.141421 0.000000
        ///v 0.461940 -0.490000 0.191342
        ///v 0.461940 0.250000 0.191342
        ///v 0.353553 -0.490000 0.353553
        ///v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string piston_base {
            get {
                return ResourceManager.GetString("piston_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;piston.blend&apos;
        ///# www.blender.org
        ///mtllib piston_head.mtl
        ///o Cylinder.005
        ///v 0.000000 0.145007 -0.500000
        ///v 0.191342 0.252500 -0.461940
        ///v 0.353553 0.252500 -0.353553
        ///v 0.461940 0.252500 -0.191342
        ///v 0.500000 0.145007 0.000000
        ///v 0.461940 0.252500 0.191342
        ///v 0.353553 0.252500 0.353553
        ///v 0.191342 0.252500 0.461940
        ///v 0.000000 0.145007 0.500000
        ///v -0.191342 0.252500 0.461940
        ///v -0.353553 0.252500 0.353554
        ///v -0.461940 0.252500 0.191342
        ///v -0.500000 0.145007 -0.000000
        ///v - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string piston_head {
            get {
                return ResourceManager.GetString("piston_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] piston_icon_png {
            get {
                object obj = ResourceManager.GetObject("piston_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;piston.blend&apos;
        ///# www.blender.org
        ///mtllib piston_shaft.mtl
        ///o Cylinder.006_Cylinder.011
        ///v 0.000000 -0.375000 -0.440000
        ///v 0.000000 0.375000 -0.440000
        ///v 0.220000 -0.375000 -0.381051
        ///v 0.220000 0.375000 -0.381051
        ///v 0.381051 -0.375000 -0.220000
        ///v 0.381051 0.375000 -0.220000
        ///v 0.440000 -0.375000 0.000000
        ///v 0.440000 0.375000 0.000000
        ///v 0.381051 -0.375000 0.220000
        ///v 0.381051 0.375000 0.220000
        ///v 0.220000 -0.375000 0.381051
        ///v 0.220000 0.375000 0.381051
        ///v 0.000000 -0.37 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string piston_shaft {
            get {
                return ResourceManager.GetString("piston_shaft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pistonblock_he_panel {
            get {
                object obj = ResourceManager.GetObject("pistonblock_he_panel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] pistonblock_he_panel_deco {
            get {
                object obj = ResourceManager.GetObject("pistonblock_he_panel_deco", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rr_floating_piston {
            get {
                object obj = ResourceManager.GetObject("rr_floating_piston", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;RR_Floating_Piston-1.blend&apos;
        ///# www.blender.org
        ///mtllib rr floating piston base.mtl
        ///o RR_Floating_Piston
        ///v -0.440008 0.143466 -0.110678
        ///v -0.450008 0.144690 -0.119976
        ///v -0.450008 0.087815 -0.119976
        ///v -0.440008 0.089039 -0.110678
        ///v -0.440008 0.077114 0.098799
        ///v -0.440008 0.078832 0.105210
        ///v -0.440008 0.082628 0.109006
        ///v -0.440008 0.089039 0.110724
        ///v -0.440008 0.143466 0.110724
        ///v -0.440008 0.149876 0.109006
        ///v -0.440008 0.153673 0.105210
        ///v -0.440008 0.155391 0.098799
        ///v -0.44000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rr_floating_piston_base {
            get {
                return ResourceManager.GetString("rr_floating_piston_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;RR_Floating_Piston.blend&apos;
        ///# www.blender.org
        ///mtllib rr floating piston head.mtl
        ///o RR_Floating_Piston.001
        ///v 0.478540 0.440000 -0.419977
        ///v 0.419976 0.440000 -0.478542
        ///v 0.410893 0.397640 -0.462809
        ///v 0.462808 0.397640 -0.410894
        ///v 0.462808 0.482370 -0.410894
        ///v 0.410893 0.482370 -0.462809
        ///v 0.424825 0.499910 -0.388965
        ///v 0.388964 0.499910 -0.424827
        ///v 0.386843 0.482370 -0.367036
        ///v 0.380394 0.482370 -0.373485
        ///v 0.373484 0.482370 -0.380395
        ///v 0.367035 0.482370 -0.386844
        ///v 0.385292 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rr_floating_piston_head {
            get {
                return ResourceManager.GetString("rr_floating_piston_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;steering regulator.blend&apos;
        ///# www.blender.org
        ///mtllib sr.mtl
        ///o Cylinder.004_Cylinder.007
        ///v -0.132023 -0.500000 0.132023
        ///v -0.132023 -0.500000 -0.132022
        ///v 0.132023 -0.500000 -0.132022
        ///v 0.132023 -0.500000 0.132023
        ///v 0.000000 -0.600000 0.000001
        ///vt 0.062266 0.062266
        ///vt 0.062266 0.000231
        ///vt 0.031251 0.031253
        ///vt 0.000234 0.062266
        ///vt 0.000234 0.000231
        ///vn -0.6038 -0.7971 0.0000
        ///vn 0.6038 -0.7971 0.0000
        ///vn 0.0000 -0.7971 -0.6038
        ///vn 0.0000 -0.7971 0.6038
        ///usemtl Mater [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sr {
            get {
                return ResourceManager.GetString("sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sr_png {
            get {
                object obj = ResourceManager.GetObject("sr_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_base.mtl
        ///o m_GSO_Block_111_Instance.001_m_GSO_Block_111_Instance.002
        ///v -0.366667 0.300000 -0.466666
        ///v -0.366667 -0.300000 -0.466667
        ///v -0.200000 -0.300000 -0.500000
        ///v -0.466667 0.300000 -0.366666
        ///v -0.500000 0.300000 -0.200000
        ///v -0.500000 0.300000 1.200000
        ///v -0.466667 0.300000 1.366667
        ///v -0.366667 -0.300000 1.466666
        ///v -0.466667 -0.300000 1.366667
        ///v -0.348148 -0.411111 -0.437037
        ///v -0.437037 -0.411111 -0.348148
        ///v - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_base {
            get {
                return ResourceManager.GetString("swivel_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;HE_Double_Rotor_Swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_double_base.mtl
        ///o HE_Double_Rotor_Swivel
        ///v 0.190577 0.313094 0.440601
        ///v 0.440577 0.313094 0.190601
        ///v 0.440577 0.313094 -0.440598
        ///v -0.440622 0.313095 -0.440598
        ///v 0.440577 0.253694 -0.499999
        ///v -0.440622 0.253694 -0.499999
        ///v 0.499977 0.253694 -0.440598
        ///v 0.499977 -0.253739 -0.440598
        ///v 0.440577 -0.253739 -0.499999
        ///v 0.499977 -0.132046 -0.132022
        ///v 0.499977 -0.132046 0.132024
        ///v 0.599977 -0.000023 0.00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_double_base {
            get {
                return ResourceManager.GetString("swivel_double_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_double_head.mtl
        ///o HE_Double_Rotor_Swivel.001
        ///v -0.277151 0.499976 -0.159998
        ///v -0.363753 0.406535 -0.209998
        ///v -0.405712 0.406535 -0.108702
        ///v -0.309119 0.499976 -0.082821
        ///v -0.226297 0.499976 -0.226273
        ///v -0.297008 0.406535 -0.296983
        ///v -0.160023 0.499976 -0.277127
        ///v -0.210023 0.406535 -0.363729
        ///v -0.082845 0.499976 -0.309095
        ///v -0.108727 0.406535 -0.405687
        ///v -0.000023 0.499976 -0.319998
        ///v -0.000023 0.406535 -0.41999 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_double_head {
            get {
                return ResourceManager.GetString("swivel_double_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 74) OBJ File: &apos;swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_head.mtl
        ///o Cube.001_Cube.002
        ///v -0.662912 0.500000 0.662913
        ///v -0.444495 0.500000 0.828130
        ///v -0.253331 0.500000 0.908641
        ///v -0.111313 0.510000 0.969217
        ///v 0.111313 0.510000 0.969217
        ///v 0.253331 0.500000 0.908641
        ///v 0.444495 0.500000 0.828130
        ///v 0.662913 0.500000 0.662913
        ///v 0.828130 0.500000 0.444495
        ///v 0.908641 0.500000 0.253331
        ///v 0.934248 0.500000 0.111313
        ///v 0.937500 0.500000 -0.000006
        ///v 0.934249 0.500000 -0.111313
        ///v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_head {
            get {
                return ResourceManager.GetString("swivel_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] swivel_png {
            get {
                object obj = ResourceManager.GetObject("swivel_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_small_base.mtl
        ///o Cube_Cube.001
        ///v -0.132021 -0.499998 0.132022
        ///v 0.132024 -0.499998 -0.132024
        ///v 0.000002 -0.599998 -0.000002
        ///v 0.132024 -0.499998 0.132022
        ///v -0.132021 -0.499998 -0.132024
        ///v 0.000000 -0.250000 -0.355000
        ///v 0.000000 0.250000 -0.355000
        ///v 0.177500 -0.250000 -0.307439
        ///v 0.177500 0.250000 -0.307439
        ///v 0.307439 -0.250000 -0.177500
        ///v 0.307439 0.250000 -0.177500
        ///v 0.355000 -0.250000 0.000000
        ///v 0.355000 0.250 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_small_base {
            get {
                return ResourceManager.GetString("swivel_small_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_small_head.mtl
        ///o Cube.001_Cube.000
        ///v 0.132021 0.499998 0.132022
        ///v -0.132024 0.499998 -0.132024
        ///v -0.000001 0.599998 -0.000001
        ///v -0.132024 0.499998 0.132022
        ///v 0.132022 0.499998 -0.132024
        ///v -0.412500 -0.250000 0.000000
        ///v -0.412500 0.250000 0.000000
        ///v -0.206250 -0.250000 -0.357235
        ///v -0.206250 0.250000 -0.357235
        ///v 0.206250 -0.250000 -0.357235
        ///v 0.206250 0.250000 -0.357235
        ///v 0.412500 -0.250000 0.000000
        ///v 0.412500 0.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_small_head {
            get {
                return ResourceManager.GetString("swivel_small_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] swivel_small_png {
            get {
                object obj = ResourceManager.GetObject("swivel_small_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;Swivel small.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_ven_base.mtl
        ///o Cube
        ///v -0.425000 0.425000 0.425000
        ///v -0.425000 0.425000 -0.425000
        ///v 0.425000 0.425000 0.425000
        ///v 0.425000 0.425000 -0.425000
        ///v -0.425000 0.159375 0.425000
        ///v -0.425000 0.159375 -0.425000
        ///v 0.425000 0.159375 -0.425000
        ///v 0.425000 0.159375 0.425000
        ///v -0.425000 0.425000 0.000000
        ///v 0.425000 0.425000 0.000000
        ///v 0.500000 0.187500 0.000000
        ///v -0.500000 0.187500 0.000000
        ///v 0.425000 0.425000 0.212500
        ///v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_ven_base {
            get {
                return ResourceManager.GetString("swivel_ven_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;Swivel small.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_ven_head.mtl
        ///o Cube.001
        ///v 0.600000 0.000000 0.000000
        ///v 0.499999 -0.132023 0.132023
        ///v 0.499999 -0.132023 -0.132023
        ///v 0.499999 0.132023 -0.132023
        ///v 0.499999 0.132023 0.132023
        ///v 0.000000 -0.159375 0.000000
        ///v 0.000000 0.159375 0.000000
        ///v -0.207414 -0.159375 -0.500743
        ///v -0.207414 0.159375 -0.500743
        ///v 0.207414 -0.159375 -0.500743
        ///v 0.207414 0.159375 -0.500743
        ///v 0.500743 -0.159375 -0.207414
        ///v 0.500743 0.159375 -0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_ven_head {
            get {
                return ResourceManager.GetString("swivel_ven_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] swivel_ven_png {
            get {
                object obj = ResourceManager.GetObject("swivel_ven_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] swivelblock_he {
            get {
                object obj = ResourceManager.GetObject("swivelblock_he", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;ven twist piston.blend&apos;
        ///# www.blender.org
        ///mtllib ven twist piston base.mtl
        ///o Cube
        ///v 0.132023 -0.499998 -0.132023
        ///v -0.132022 -0.499998 -0.132023
        ///v 0.132023 -0.499998 0.132023
        ///v 0.000001 -0.599998 -0.000000
        ///v -0.132022 -0.499998 0.132023
        ///v 0.225000 -0.500000 -0.300000
        ///v 0.300000 -0.500000 -0.225000
        ///v 0.225000 0.100000 0.225000
        ///v 0.300000 -0.500000 0.225000
        ///v 0.225000 -0.500000 0.300000
        ///v -0.300000 -0.500000 -0.225000
        ///v -0.225000 -0.500000 -0.300000
        ///v -0.225000 0.100000 0.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ven_twist_piston_base {
            get {
                return ResourceManager.GetString("ven_twist_piston_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;ven twist piston.blend&apos;
        ///# www.blender.org
        ///mtllib ven twist piston head.mtl
        ///o Cube_AP.001
        ///v -0.225000 0.200000 0.225000
        ///v -0.225000 0.275000 0.300000
        ///v -0.300000 0.275000 0.225000
        ///v -0.300000 0.500000 0.225000
        ///v -0.225000 0.500000 0.300000
        ///v -0.225000 0.200000 -0.225000
        ///v -0.300000 0.275000 -0.225000
        ///v -0.225000 0.275000 -0.300000
        ///v -0.225000 0.500000 -0.300000
        ///v -0.300000 0.500000 -0.225000
        ///v 0.225000 0.200000 0.225000
        ///v 0.300000 0.275000 0.225000
        ///v 0.225000 0.275000 0.30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ven_twist_piston_head {
            get {
                return ResourceManager.GetString("ven_twist_piston_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ven_twist_piston_png {
            get {
                object obj = ResourceManager.GetObject("ven_twist_piston_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;ven twist piston.blend&apos;
        ///# www.blender.org
        ///mtllib ven twist piston shaft 1.mtl
        ///o Cylinder_Cylinder.003
        ///v -0.000000 -0.500000 -0.214200
        ///v -0.136316 0.400000 -0.157736
        ///v 0.151462 -0.500000 -0.151462
        ///v 0.015146 0.400000 -0.207926
        ///v 0.214200 -0.500000 0.000000
        ///v 0.157736 0.400000 -0.136316
        ///v 0.151462 -0.500000 0.151462
        ///v 0.207926 0.400000 0.015146
        ///v -0.000000 -0.500000 0.214200
        ///v 0.136316 0.400000 0.157736
        ///v -0.151462 -0.500000 0.151462
        ///v -0.015146 0.400000 0.207926
        ///v -0.21420 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ven_twist_piston_shaft_1 {
            get {
                return ResourceManager.GetString("ven_twist_piston_shaft_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.81 (sub 16) OBJ File: &apos;ven twist piston.blend&apos;
        ///# www.blender.org
        ///mtllib ven twist piston shaft 2.mtl
        ///o Cylinder.001_Cylinder.004
        ///v 0.066893 -0.500000 -0.161494
        ///v -0.066893 0.500000 -0.161494
        ///v 0.161494 -0.500000 -0.066893
        ///v 0.066893 0.500000 -0.161494
        ///v 0.161494 -0.500000 0.066893
        ///v 0.161494 0.500000 -0.066893
        ///v 0.066893 -0.500000 0.161494
        ///v 0.161494 0.500000 0.066893
        ///v -0.066893 -0.500000 0.161494
        ///v 0.066893 0.500000 0.161494
        ///v -0.161494 -0.500000 0.066893
        ///v -0.066893 0.500000 0.161494
        ///v -0.16 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ven_twist_piston_shaft_2 {
            get {
                return ResourceManager.GetString("ven_twist_piston_shaft_2", resourceCulture);
            }
        }
    }
}
