//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Block.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Control_Block.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;BFCab.blend&apos;
        ///# www.blender.org
        ///mtllib BFCab.mtl
        ///o m_BF_Streamline_111.000
        ///v 0.474894 0.468360 -0.475100
        ///v -0.475107 0.468360 -0.474880
        ///v 0.474946 -0.337101 -0.475050
        ///v -0.475055 -0.337101 -0.474940
        ///v 0.474998 -0.337101 0.482365
        ///v -0.475002 -0.337101 0.482365
        ///v 0.474946 -0.097373 -0.475050
        ///v -0.000002 -0.337101 0.482365
        ///v 0.474972 -0.337101 -0.008842
        ///v -0.000028 -0.337101 0.091185
        ///v -0.475029 -0.337101 -0.008787
        ///v 0.118702 -0.337101 -0.475022
        ///v -0.118798 -0.337101 -0.474967 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BFCab {
            get {
                return ResourceManager.GetString("BFCab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BFCab_png {
            get {
                object obj = ResourceManager.GetObject("BFCab_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;BFCab.blend&apos;
        ///# www.blender.org
        ///mtllib BFCab_wheel.mtl
        ///o m_GSO_Cab_111_Tyre_4.004_m_GSO_Cab_111_Tyre_4.001
        ///v -0.093644 0.000000 -0.157456
        ///v -0.093644 0.111339 -0.111338
        ///v 0.093644 0.111339 -0.111338
        ///v 0.093644 0.000000 -0.157456
        ///v 0.093644 0.157457 0.000000
        ///v -0.093644 0.157457 0.000000
        ///v -0.093644 -0.111338 -0.111338
        ///v 0.093644 -0.111338 -0.111338
        ///v -0.093644 -0.157456 -0.000000
        ///v 0.093644 -0.157456 -0.000000
        ///v -0.093644 -0.111338 0.111339
        ///v 0.093644 -0.111338 0.111339
        ///v - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BFCab_wheel {
            get {
                return ResourceManager.GetString("BFCab_wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;BFpiston.blend&apos;
        ///# www.blender.org
        ///mtllib BFp_blockbottom.mtl
        ///o m_BF_MotionEngine_Linear_112_Base_Instance
        ///v 0.101537 0.499999 -0.378939
        ///v 0.277403 0.499999 -0.277403
        ///v -0.277403 0.499999 -0.277403
        ///v -0.146954 -0.314892 -0.500000
        ///v 0.107356 -0.428834 -0.500000
        ///v 0.146954 -0.314892 -0.500000
        ///v -0.107356 -0.428834 -0.499999
        ///v 0.126918 -0.500001 -0.428833
        ///v 0.366017 -0.428834 -0.366017
        ///v -0.500000 -0.428834 -0.107355
        ///v -0.500000 -0.314892 -0.146953
        ///v -0.500000 -0.428834 0.1073 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BFp_blockbottom {
            get {
                return ResourceManager.GetString("BFp_blockbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;BFpiston.blend&apos;
        ///# www.blender.org
        ///mtllib BFp_blocktop.mtl
        ///o m_BF_MotionEngine_Linear_112_Base_Instance.001
        ///v -0.146954 0.428834 -0.500000
        ///v -0.366017 0.428834 -0.366018
        ///v 0.126918 0.500000 -0.428834
        ///v -0.500000 0.428834 -0.146954
        ///v -0.428834 0.500000 -0.126919
        ///v 0.146954 0.428834 0.500000
        ///v -0.146954 0.428834 0.500000
        ///v -0.315695 0.500000 0.315695
        ///v -0.126918 0.500000 0.428833
        ///v 0.126918 0.500000 0.428833
        ///v -0.366017 0.428834 0.366017
        ///v -0.500000 0.428834 0.146953
        ///v 0.1469 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BFp_blocktop {
            get {
                return ResourceManager.GetString("BFp_blocktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BFp_png {
            get {
                object obj = ResourceManager.GetObject("BFp_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] friction_pad_gc_big_png {
            get {
                object obj = ResourceManager.GetObject("friction_pad_gc_big_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] friction_pad_gc_small_png {
            get {
                object obj = ResourceManager.GetObject("friction_pad_gc_small_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GC friction pad.blend&apos;
        ///# www.blender.org
        ///mtllib GCfrictionpadbig.mtl
        ///o m_BF_Block_Faired_111_Instance.001
        ///v -0.000002 0.600000 1.000000
        ///v 0.132021 0.500000 1.132023
        ///v 0.132021 0.500000 0.867977
        ///v -0.132024 0.500000 1.132023
        ///v -0.132024 0.500000 0.867977
        ///v 1.300000 0.300000 -0.300000
        ///v 1.300000 0.300000 1.300000
        ///v -0.300000 0.300000 1.300000
        ///v -0.300000 0.300000 -0.300000
        ///v 0.900000 0.100000 0.100000
        ///v 0.900000 0.100000 0.900000
        ///v 0.100000 0.100000 0.100000
        ///v 0.100000 0.100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GCfrictionpadbig {
            get {
                return ResourceManager.GetString("GCfrictionpadbig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GC friction pad.blend&apos;
        ///# www.blender.org
        ///mtllib GCfrictionpad.mtl
        ///o Cylinder
        ///v 0.000000 0.500000 0.000000
        ///v 0.000000 0.412500 -0.500000
        ///v 0.000000 0.500000 -0.500000
        ///v 0.191342 0.412500 -0.461940
        ///v 0.191342 0.500000 -0.461940
        ///v 0.353553 0.412500 -0.353553
        ///v 0.353553 0.500000 -0.353553
        ///v 0.461940 0.412500 -0.191342
        ///v 0.461940 0.500000 -0.191342
        ///v 0.500000 0.412500 0.000000
        ///v 0.500000 0.500000 0.000000
        ///v 0.461940 0.412500 0.191342
        ///v 0.461940 0.500000 0.191342
        ///v 0.353553 0.41 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GCfrictionpadsmall {
            get {
                return ResourceManager.GetString("GCfrictionpadsmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GEO_piston.blend&apos;
        ///# www.blender.org
        ///mtllib GEOp_blockbottom.mtl
        ///o geo_block_bottom
        ///v -0.258274 0.344012 0.659851
        ///v -0.258274 0.557951 0.659851
        ///v -0.371306 0.557951 0.613032
        ///v -0.371306 0.344012 0.613032
        ///v -0.418125 0.557951 0.500000
        ///v -0.418125 0.344012 0.500000
        ///v -0.371306 0.557951 0.386968
        ///v -0.371306 0.344012 0.386968
        ///v -0.258274 0.557951 0.340149
        ///v -0.258274 0.344012 0.340149
        ///v 0.030684 0.344012 0.659851
        ///v 0.030684 0.557951 0.659851
        ///v 0.030684 0.557951 0.340149
        ///v 0.030 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEOp_blockbottom {
            get {
                return ResourceManager.GetString("GEOp_blockbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GEO_piston.blend&apos;
        ///# www.blender.org
        ///mtllib GEOp_blocktop.mtl
        ///o geo_block_top
        ///v 1.500000 0.552534 -0.045250
        ///v 1.500000 0.552534 -0.300020
        ///v 1.500000 0.965657 -0.300020
        ///v 1.441378 0.552534 -0.045250
        ///v 1.500000 0.369114 0.103227
        ///v 1.441378 0.369114 0.103227
        ///v 1.300020 1.300020 -0.500000
        ///v 1.300020 1.500000 -0.300020
        ///v 1.500000 1.300020 -0.300020
        ///v 1.045250 0.552534 -0.500000
        ///v 0.896773 0.369114 -0.500000
        ///v 0.103227 0.369114 -0.500000
        ///v -0.045250 0.552534 -0.500000
        ///v 1.500000  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEOp_blocktop {
            get {
                return ResourceManager.GetString("GEOp_blocktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GEOp_icon_png {
            get {
                object obj = ResourceManager.GetObject("GEOp_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GEO_piston.blend&apos;
        ///# www.blender.org
        ///mtllib GEOp_shaftbottom.mtl
        ///o geo_piston_bottom
        ///v 1.185176 -0.160939 0.104413
        ///v 0.895587 -0.160939 -0.185176
        ///v 0.895587 1.131227 -0.185176
        ///v 1.185176 1.131227 0.104413
        ///v 0.500000 -0.160939 -0.291174
        ///v 0.500000 1.131227 -0.291174
        ///v 0.104413 -0.160939 -0.185176
        ///v 0.104413 1.131227 -0.185176
        ///v -0.185176 -0.160939 0.104413
        ///v -0.185176 1.131227 0.104413
        ///v -0.291174 -0.160939 0.500000
        ///v -0.291174 1.131227 0.500000
        ///v -0.185176 -0.160939 0.89558 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEOp_shaftbottom {
            get {
                return ResourceManager.GetString("GEOp_shaftbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;GEO_piston.blend&apos;
        ///# www.blender.org
        ///mtllib GEOp_shafttop.mtl
        ///o geo_piston_top
        ///v 1.064939 0.513169 0.173832
        ///v 0.826168 0.513169 -0.064939
        ///v 0.826168 1.486831 -0.064939
        ///v 1.064939 1.486831 0.173832
        ///v 0.500000 0.513169 -0.152335
        ///v 0.500000 1.486831 -0.152335
        ///v 0.173832 0.513169 -0.064939
        ///v 0.173832 1.486831 -0.064939
        ///v -0.064939 0.513169 0.173832
        ///v -0.064939 1.486831 0.173832
        ///v -0.152335 0.513169 0.500000
        ///v -0.152335 1.486831 0.500000
        ///v -0.064939 0.513169 0.826168
        ///v -0.064939 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GEOp_shafttop {
            get {
                return ResourceManager.GetString("GEOp_shafttop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_blockbottom.mtl
        ///o the_node.014_tri_420_geometry.000
        ///v -0.468440 0.374719 -0.312560
        ///v -0.468440 -0.375040 -0.312146
        ///v -0.468440 -0.000159 0.062318
        ///v 0.468759 0.374719 -0.468760
        ///v 0.312559 0.374719 -0.468760
        ///v 0.312559 0.374719 -0.312560
        ///v 0.468759 0.374719 -0.312560
        ///v 0.468759 -0.000159 0.062318
        ///v 0.468759 -0.375040 -0.312145
        ///v -0.312240 0.374719 -0.468760
        ///v -0.312240 0.374719 -0.312560
        ///v 0.312559 -0.375040 -0.468760
        ///v -0.312240 -0.375040 -0.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_blockbottom {
            get {
                return ResourceManager.GetString("HEp_blockbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_blocktop.mtl
        ///o the_node.002_tri_420_geometry.000
        ///v -0.468440 -0.374719 0.312560
        ///v -0.468440 0.375040 0.312145
        ///v -0.468440 0.000159 -0.062319
        ///v 0.468759 -0.374719 0.468760
        ///v 0.312559 -0.374719 0.468760
        ///v 0.312559 -0.374719 0.312560
        ///v 0.468759 -0.374719 0.312560
        ///v 0.468759 0.000159 -0.062319
        ///v 0.468759 0.375040 0.312145
        ///v -0.312240 -0.374719 0.468760
        ///v -0.312240 -0.374719 0.312560
        ///v 0.312559 0.375040 0.468760
        ///v -0.312240 0.375040 0.468760
        ///v -0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_blocktop {
            get {
                return ResourceManager.GetString("HEp_blocktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HEp_icon_png {
            get {
                object obj = ResourceManager.GetObject("HEp_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_shaftbottom.mtl
        ///o the_node.006_tri_420_geometry.001
        ///v -0.327860 -0.000321 0.327859
        ///v -0.437200 -0.000321 0.327859
        ///v -0.437200 -0.000321 0.437199
        ///v -0.327860 -0.000321 0.437199
        ///v 0.437519 -0.500160 -0.328180
        ///v 0.437519 -0.000320 -0.328180
        ///v 0.437519 -0.000320 -0.000160
        ///v 0.437519 -0.500160 -0.000160
        ///v -0.327860 -0.000321 -0.328180
        ///v -0.437200 -0.000321 -0.328180
        ///v -0.437200 -0.000321 -0.000160
        ///v -0.327860 -0.000321 -0.000160
        ///v -0.437200 -0.500 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_shaftbottom {
            get {
                return ResourceManager.GetString("HEp_shaftbottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;HE_piston.blend&apos;
        ///# www.blender.org
        ///mtllib HEp_shaftmidb.mtl
        ///o the_node.018_tri_420_geometry.020
        ///v 0.312559 0.499359 0.312239
        ///v -0.312240 -0.437841 -0.312560
        ///v 0.312559 -0.437840 -0.312560
        ///v -0.312240 -0.437841 0.312239
        ///v 0.312559 -0.437840 0.312240
        ///v -0.312240 0.499359 -0.312560
        ///v 0.312559 0.499359 -0.312560
        ///v -0.312240 0.499359 0.312239
        ///v -0.312240 -0.437841 -0.000160
        ///v 0.312559 0.499359 -0.000160
        ///v 0.312559 -0.437840 -0.000160
        ///v -0.312240 0.499359 -0.000160
        ///v -0.312240 - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_shaftmidb {
            get {
                return ResourceManager.GetString("HEp_shaftmidb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_shaftmidt.mtl
        ///o the_node.019_tri_420_geometry.021
        ///v 0.281319 -0.500641 -0.211030
        ///v 0.281319 0.436559 -0.211030
        ///v 0.281319 0.436559 -0.000161
        ///v 0.281319 -0.500641 -0.000160
        ///v 0.281319 0.436559 0.210709
        ///v 0.281319 -0.500641 0.210709
        ///v 0.211029 -0.500641 -0.281320
        ///v 0.000159 -0.500641 -0.281320
        ///v 0.000159 0.436559 -0.281320
        ///v 0.211029 0.436559 -0.281320
        ///v -0.210710 -0.500641 -0.281320
        ///v -0.210711 0.436559 -0.281320
        ///v -0.281000 -0.500641 -0.21103 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_shaftmidt {
            get {
                return ResourceManager.GetString("HEp_shaftmidt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib HEp_shafttop.mtl
        ///o the_node.013_tri_420_geometry.002
        ///v -0.327860 0.000321 -0.327860
        ///v -0.437200 0.000321 -0.327860
        ///v -0.437200 0.000321 -0.437200
        ///v -0.327860 0.000321 -0.437200
        ///v 0.437519 0.500160 0.328180
        ///v 0.437519 0.000321 0.328180
        ///v 0.437519 0.000321 0.000160
        ///v 0.437519 0.500160 0.000160
        ///v -0.327860 0.000321 0.328180
        ///v -0.437200 0.000321 0.328180
        ///v -0.437200 0.000321 0.000160
        ///v -0.327860 0.000321 0.000160
        ///v -0.437200 0.500160 0.328180
        ///v -0.43 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEp_shafttop {
            get {
                return ResourceManager.GetString("HEp_shafttop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib mtmag ball.mtl
        ///o m_BF_Block_Faired_111_Instance.001
        ///v -0.450001 -0.400000 -0.499999
        ///v 0.449999 -0.400000 -0.500000
        ///v 0.499999 -0.400000 -0.450001
        ///v -0.500001 -0.400000 -0.449999
        ///v -0.500000 -0.400000 0.450001
        ///v 0.450000 -0.400000 0.499999
        ///v -0.450000 -0.400000 0.500000
        ///v 0.500000 -0.400000 0.449999
        ///v -0.000000 -0.160000 -0.003982
        ///v 0.499999 -0.500000 -0.500001
        ///v -0.500001 -0.500000 -0.500000
        ///v -0.500000 -0.500000 0.500000
        ///v 0.500000 -0.500000 0.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_ball {
            get {
                return ResourceManager.GetString("mtmag_ball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib mtmag ball collider.mtl
        ///o Cone
        ///v 0.000000 -0.500000 -0.500000
        ///v 0.000000 -0.200000 -0.250000
        ///v 0.353553 -0.500000 -0.353553
        ///v 0.176777 -0.200000 -0.176777
        ///v 0.500000 -0.500000 0.000000
        ///v 0.250000 -0.200000 0.000000
        ///v 0.353553 -0.500000 0.353553
        ///v 0.176777 -0.200000 0.176777
        ///v -0.000000 -0.500000 0.500000
        ///v -0.000000 -0.200000 0.250000
        ///v -0.353553 -0.500000 0.353553
        ///v -0.176777 -0.200000 0.176777
        ///v -0.500000 -0.500000 -0.000000
        ///v -0.250000 -0.2000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_ball_collider {
            get {
                return ResourceManager.GetString("mtmag_ball_collider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 47) OBJ File: &apos;Ball.blend&apos;
        ///# www.blender.org
        ///mtllib mtmag ball collider large.mtl
        ///o Cone
        ///v 0.500000 -0.500000 -0.207106
        ///v 0.500000 0.100000 -0.000000
        ///v 0.853554 0.100000 0.146446
        ///v 1.207106 -0.500000 -0.207106
        ///v 1.000000 0.100000 0.500000
        ///v 1.207106 -0.500000 0.500000
        ///v 0.853554 0.100000 0.853554
        ///v 1.207106 -0.500000 1.207106
        ///v 0.500000 0.100000 1.000000
        ///v 0.500000 -0.500000 1.207106
        ///v 0.146446 0.100000 0.853554
        ///v -0.207106 -0.500000 1.207106
        ///v 0.000000 0.100000 0.500000
        ///v -0.207106 -0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_ball_collider_large {
            get {
                return ResourceManager.GetString("mtmag_ball_collider_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.80 (sub 47) OBJ File: &apos;Ball.blend&apos;
        ///# www.blender.org
        ///mtllib mtmag ball large.mtl
        ///o m_BF_Block_Faired_111_Instance.001
        ///v 0.786182 -0.247577 1.190903
        ///v 0.213819 -0.247577 -0.190903
        ///v 0.500000 -0.250000 1.191324
        ///v 0.786181 -0.247577 -0.190903
        ///v 0.213819 -0.247577 1.190903
        ///v 1.190903 -0.247577 0.213819
        ///v 0.500000 -0.250000 -0.191324
        ///v 0.500000 -0.500000 -0.145367
        ///v 0.189096 -0.497458 -0.145108
        ///v -0.146268 -0.497472 -0.145367
        ///v -0.145340 -0.497579 0.190105
        ///v -0.145930 -0.500000 0.500000
        ///v -0.145716  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_ball_large {
            get {
                return ResourceManager.GetString("mtmag_ball_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mtmag_ball_large_png {
            get {
                object obj = ResourceManager.GetObject("mtmag_ball_large_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] mtmag_ball_png {
            get {
                object obj = ResourceManager.GetObject("mtmag_ball_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib mtmag fixed.mtl
        ///o m_BF_Block_Faired_111_Instance.001_m_BF_Block_Faired_111_Instance.009
        ///v 0.450000 -0.000000 0.125000
        ///v -0.405000 -0.000000 -0.450000
        ///v 0.125000 -0.000000 0.450000
        ///v 0.450000 -0.000000 0.405000
        ///v 0.450000 -0.000000 -0.405000
        ///v -0.450000 -0.000000 -0.125000
        ///v -0.405000 -0.000000 0.450000
        ///v 0.125000 -0.000000 -0.450000
        ///v -0.125000 -0.000000 -0.450000
        ///v -0.450000 -0.000000 0.405000
        ///v 0.450000 -0.000000 -0.125000
        ///v -0.450000 -0.000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_fixed {
            get {
                return ResourceManager.GetString("mtmag_fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;&apos;
        ///# www.blender.org
        ///mtllib mtmag swivel large.mtl
        ///o Plane.001
        ///v 0.146447 -0.500000 1.500000
        ///v 0.323223 -0.500000 1.500000
        ///v 0.423223 -0.300003 1.500000
        ///v 0.146447 -0.050003 1.499317
        ///v 0.500000 -0.064148 1.400322
        ///v 0.500000 0.399989 1.390877
        ///v 0.853553 0.399989 1.340877
        ///v 0.853553 -0.064148 1.400322
        ///v 0.500000 -0.050003 1.499317
        ///v 0.853553 -0.050003 1.499317
        ///v 0.853553 0.399993 1.418785
        ///v 0.853553 -0.500000 1.500000
        ///v 0.853553 -0.500000 1.401005
        ///v 0.146447 -0.500000 1.40100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtmag_swivel_large {
            get {
                return ResourceManager.GetString("mtmag_swivel_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;piston.blend&apos;
        ///# www.blender.org
        ///mtllib piston_base.mtl
        ///o Cylinder
        ///v 0.000000 -0.490000 -0.500000
        ///v 0.000000 0.141421 -0.500000
        ///v 0.191342 -0.490000 -0.461940
        ///v 0.191342 0.250000 -0.461940
        ///v 0.353553 -0.490000 -0.353553
        ///v 0.353553 0.250000 -0.353553
        ///v 0.461940 -0.490000 -0.191342
        ///v 0.461940 0.250000 -0.191342
        ///v 0.500000 -0.490000 0.000000
        ///v 0.500000 0.141421 0.000000
        ///v 0.461940 -0.490000 0.191342
        ///v 0.461940 0.250000 0.191342
        ///v 0.353553 -0.490000 0.353553
        ///v 0.353553 0.250000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string piston_base {
            get {
                return ResourceManager.GetString("piston_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;piston.blend&apos;
        ///# www.blender.org
        ///mtllib piston_head.mtl
        ///o Cylinder.005
        ///v 0.000000 0.141421 -0.500000
        ///v 0.191342 0.250000 -0.461940
        ///v 0.353553 0.250000 -0.353553
        ///v 0.461940 0.250000 -0.191342
        ///v 0.500000 0.141421 0.000000
        ///v 0.461940 0.250000 0.191342
        ///v 0.353553 0.250000 0.353553
        ///v 0.191342 0.250000 0.461940
        ///v 0.000000 0.141421 0.500000
        ///v -0.191342 0.250000 0.461940
        ///v -0.353553 0.250000 0.353554
        ///v -0.461940 0.250000 0.191342
        ///v -0.500000 0.141421 -0.000000
        ///v -0.461940 0.250000  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string piston_head {
            get {
                return ResourceManager.GetString("piston_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] piston_icon_png {
            get {
                object obj = ResourceManager.GetObject("piston_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///#
        ///#
        ///
        ///mtllib piston_shaft.mtl
        ///
        ///
        ///#
        ///#  Mesh
        ///#
        ///g  Mesh
        ///
        ///
        ///#
        ///#  Mesh_None
        ///#
        ///usemtl  Mesh_None
        ///
        ///v 0.000000 0.337500 -0.440000
        ///v 0.000000 0.375000 -0.440000
        ///v 0.220000 0.375000 -0.381051
        ///v 0.220000 0.337500 -0.381051
        ///v 0.381051 0.375000 -0.220000
        ///v 0.381051 0.337500 -0.220000
        ///v 0.440000 0.375000 0.000000
        ///v 0.440000 0.337500 0.000000
        ///v 0.381051 0.375000 0.220000
        ///v 0.381051 0.337500 0.220000
        ///v 0.220000 0.375000 0.381051
        ///v 0.220000 0.337500 0.381051
        ///v 0.000000 0.375000 0.440000
        ///v 0.000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string piston_shaft {
            get {
                return ResourceManager.GetString("piston_shaft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;steering regulator.blend&apos;
        ///# www.blender.org
        ///mtllib sr.mtl
        ///o Cylinder.004_Cylinder.007
        ///v -0.132023 -0.500000 0.132023
        ///v -0.132023 -0.500000 -0.132022
        ///v 0.132023 -0.500000 -0.132022
        ///v 0.132023 -0.500000 0.132023
        ///v 0.000000 -0.600000 0.000001
        ///vt 0.062266 0.062266
        ///vt 0.062266 0.000231
        ///vt 0.031251 0.031253
        ///vt 0.000234 0.062266
        ///vt 0.000234 0.000231
        ///vn -0.6038 -0.7971 0.0000
        ///vn 0.6038 -0.7971 0.0000
        ///vn 0.0000 -0.7971 -0.6038
        ///vn 0.0000 -0.7971 0.6038
        ///usemtl Material.001
        ///s off
        ///f 1/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sr {
            get {
                return ResourceManager.GetString("sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sr_png {
            get {
                object obj = ResourceManager.GetObject("sr_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_base.mtl
        ///o Cube_Cube.001
        ///v -0.375000 -0.437500 1.375000
        ///v -0.375000 0.437500 1.375000
        ///v -0.375000 -0.437500 -0.375000
        ///v -0.375000 0.437500 -0.375000
        ///v 1.375000 -0.437500 1.375000
        ///v 1.375000 0.437500 1.375000
        ///v 1.375000 -0.437500 -0.375000
        ///v 1.375000 0.437500 -0.375000
        ///v 0.500000 0.500000 1.500000
        ///v -0.500000 0.500000 0.500000
        ///v 0.500000 0.500000 -0.500000
        ///v 1.500000 0.500000 0.499994
        ///v -0.383339 0.500000 0.974128
        ///v -0.469217 0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_base {
            get {
                return ResourceManager.GetString("swivel_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_head.mtl
        ///o Cube.001_Cube.002
        ///v -0.662912 0.500000 0.662913
        ///v -0.444495 0.500000 0.828130
        ///v -0.253331 0.500000 0.908641
        ///v -0.111313 0.500000 0.969217
        ///v -0.000000 0.500000 1.000000
        ///v 0.111313 0.500000 0.969217
        ///v 0.253331 0.500000 0.908641
        ///v 0.444495 0.500000 0.828130
        ///v 0.662913 0.500000 0.662913
        ///v 0.828130 0.500000 0.444495
        ///v 0.908641 0.500000 0.253331
        ///v 0.934248 0.500000 0.111313
        ///v 0.937500 0.500000 -0.000006
        ///v 0.934249 0.500000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_head {
            get {
                return ResourceManager.GetString("swivel_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] swivel_png {
            get {
                object obj = ResourceManager.GetObject("swivel_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_small_base.mtl
        ///o Cube_Cube.001
        ///v -0.132021 -0.499998 0.132022
        ///v 0.132024 -0.499998 -0.132024
        ///v 0.000002 -0.599998 -0.000002
        ///v 0.132024 -0.499998 0.132022
        ///v -0.132021 -0.499998 -0.132024
        ///v 0.000000 -0.250000 -0.355000
        ///v 0.000000 0.250000 -0.355000
        ///v 0.177500 -0.250000 -0.307439
        ///v 0.177500 0.250000 -0.307439
        ///v 0.307439 -0.250000 -0.177500
        ///v 0.307439 0.250000 -0.177500
        ///v 0.355000 -0.250000 0.000000
        ///v 0.355000 0.250000 0.000000
        ///v 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_small_base {
            get {
                return ResourceManager.GetString("swivel_small_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;swivel.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_small_head.mtl
        ///o Cube.001_Cube.000
        ///v 0.132021 0.499998 0.132022
        ///v -0.132024 0.499998 -0.132024
        ///v -0.000001 0.599998 -0.000001
        ///v -0.132024 0.499998 0.132022
        ///v 0.132022 0.499998 -0.132024
        ///v -0.412500 -0.250000 0.000000
        ///v -0.412500 0.250000 0.000000
        ///v -0.206250 -0.250000 -0.357235
        ///v -0.206250 0.250000 -0.357235
        ///v 0.206250 -0.250000 -0.357235
        ///v 0.206250 0.250000 -0.357235
        ///v 0.412500 -0.250000 0.000000
        ///v 0.412500 0.250000 0.000000
        ///v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_small_head {
            get {
                return ResourceManager.GetString("swivel_small_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] swivel_small_png {
            get {
                object obj = ResourceManager.GetObject("swivel_small_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;Swivel small.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_ven_base.mtl
        ///o Cube
        ///v -0.425000 0.425000 0.425000
        ///v -0.425000 0.425000 -0.425000
        ///v 0.425000 0.425000 0.425000
        ///v 0.425000 0.425000 -0.425000
        ///v -0.425000 0.159375 0.425000
        ///v -0.425000 0.159375 -0.425000
        ///v 0.425000 0.159375 -0.425000
        ///v 0.425000 0.159375 0.425000
        ///v -0.425000 0.425000 0.000000
        ///v 0.425000 0.425000 0.000000
        ///v 0.500000 0.187500 0.000000
        ///v -0.500000 0.187500 0.000000
        ///v 0.425000 0.425000 0.212500
        ///v 0.500000 0.18750 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_ven_base {
            get {
                return ResourceManager.GetString("swivel_ven_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;Swivel small.blend&apos;
        ///# www.blender.org
        ///mtllib swivel_ven_head.mtl
        ///o Cube.001
        ///v 0.600000 0.000000 0.000000
        ///v 0.499999 -0.132023 0.132023
        ///v 0.499999 -0.132023 -0.132023
        ///v 0.499999 0.132023 -0.132023
        ///v 0.499999 0.132023 0.132023
        ///v 0.000000 -0.159375 0.000000
        ///v 0.000000 0.159375 0.000000
        ///v -0.207414 -0.159375 -0.500743
        ///v -0.207414 0.159375 -0.500743
        ///v 0.207414 -0.159375 -0.500743
        ///v 0.207414 0.159375 -0.500743
        ///v 0.500743 -0.159375 -0.207414
        ///v 0.500743 0.159375 -0.207414
        ///v 0.5007 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string swivel_ven_head {
            get {
                return ResourceManager.GetString("swivel_ven_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] swivel_ven_png {
            get {
                object obj = ResourceManager.GetObject("swivel_ven_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
