//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Control_Block.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Control_Block.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;piston.blend&apos;
        ///# www.blender.org
        ///mtllib piston_base.mtl
        ///o Cylinder
        ///v 0.000000 -0.490000 -0.500000
        ///v 0.000000 0.141421 -0.500000
        ///v 0.191342 -0.490000 -0.461940
        ///v 0.191342 0.250000 -0.461940
        ///v 0.353553 -0.490000 -0.353553
        ///v 0.353553 0.250000 -0.353553
        ///v 0.461940 -0.490000 -0.191342
        ///v 0.461940 0.250000 -0.191342
        ///v 0.500000 -0.490000 0.000000
        ///v 0.500000 0.141421 0.000000
        ///v 0.461940 -0.490000 0.191342
        ///v 0.461940 0.250000 0.191342
        ///v 0.353553 -0.490000 0.353553
        ///v 0.353553 0.250000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string piston_base {
            get {
                return ResourceManager.GetString("piston_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;piston.blend&apos;
        ///# www.blender.org
        ///mtllib piston_head.mtl
        ///o Cylinder.005
        ///v 0.000000 0.141421 -0.500000
        ///v 0.191342 0.250000 -0.461940
        ///v 0.353553 0.250000 -0.353553
        ///v 0.461940 0.250000 -0.191342
        ///v 0.500000 0.141421 0.000000
        ///v 0.461940 0.250000 0.191342
        ///v 0.353553 0.250000 0.353553
        ///v 0.191342 0.250000 0.461940
        ///v 0.000000 0.141421 0.500000
        ///v -0.191342 0.250000 0.461940
        ///v -0.353553 0.250000 0.353554
        ///v -0.461940 0.250000 0.191342
        ///v -0.500000 0.141421 -0.000000
        ///v -0.461940 0.250000  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string piston_head {
            get {
                return ResourceManager.GetString("piston_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] piston_icon_png {
            get {
                object obj = ResourceManager.GetObject("piston_icon_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///#
        ///#
        ///
        ///mtllib piston_shaft.mtl
        ///
        ///
        ///#
        ///#  Mesh
        ///#
        ///g  Mesh
        ///
        ///
        ///#
        ///#  Mesh_None
        ///#
        ///usemtl  Mesh_None
        ///
        ///v 0.000000 0.337500 -0.440000
        ///v 0.000000 0.375000 -0.440000
        ///v 0.220000 0.375000 -0.381051
        ///v 0.220000 0.337500 -0.381051
        ///v 0.381051 0.375000 -0.220000
        ///v 0.381051 0.337500 -0.220000
        ///v 0.440000 0.375000 0.000000
        ///v 0.440000 0.337500 0.000000
        ///v 0.381051 0.375000 0.220000
        ///v 0.381051 0.337500 0.220000
        ///v 0.220000 0.375000 0.381051
        ///v 0.220000 0.337500 0.381051
        ///v 0.000000 0.375000 0.440000
        ///v 0.000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string piston_shaft {
            get {
                return ResourceManager.GetString("piston_shaft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Blender v2.79 (sub 0) OBJ File: &apos;steering regulator.blend&apos;
        ///# www.blender.org
        ///mtllib sr.mtl
        ///o Cylinder.004_Cylinder.007
        ///v -0.132023 -0.500000 0.132023
        ///v -0.132023 -0.500000 -0.132022
        ///v 0.132023 -0.500000 -0.132022
        ///v 0.132023 -0.500000 0.132023
        ///v 0.000000 -0.600000 0.000001
        ///vt 0.062266 0.062266
        ///vt 0.062266 0.000231
        ///vt 0.031251 0.031253
        ///vt 0.000234 0.062266
        ///vt 0.000234 0.000231
        ///vn -0.6038 -0.7971 0.0000
        ///vn 0.6038 -0.7971 0.0000
        ///vn 0.0000 -0.7971 -0.6038
        ///vn 0.0000 -0.7971 0.6038
        ///usemtl Material.001
        ///s off
        ///f 1/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sr {
            get {
                return ResourceManager.GetString("sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sr_png {
            get {
                object obj = ResourceManager.GetObject("sr_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
